services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rooted1622
      POSTGRES_DB: bus_auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-api:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"  # 🔁 Changed from build/start to dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  pgdata:
